_select_data:
  garment_types:
    - hat
    - top
collections_config:
  products:
    _enabled_editors:
      - data
    output: true
    icon: shopping_cart
    schemas:
      default:
        path: schemas/products.md
